name: CI/CD

on:
  push:
    paths-ignore:
      - .gitignore
      - README.md

  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: 'true'
          refresh-cli: 'false'

      - name: Verify go version
        run: devbox run -- go version

      - name: Start colima
        run: devbox run -- colima start --vm-type=qemu --disk=10 --arch=aarch64 --network-address

      - name: Verify docker
        run: devbox run -- docker ps